# Generated by Django 3.0.8 on 2020-07-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0003_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='music_id',
            new_name='video_id',
        ),
    ]
